/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DINManager } from "./DINManager";
export * as factories from "./factories";
export { DINManager__factory } from "./factories/DINManager__factory";
